# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e74935a7aecd35fdaece482273a7e90103ad70c10fd0a0ebcea8e542e11e6df120942dbc16f1899e201e8b9f0b26bd89e25784e60e6bf245961209a4b4336a6

test:
  secret_key_base: 4b51b73b3a87acf448e0a756ea0d8c73a188299c3069fb285a7fbeb5fbbc965ac11da5d504888c1ec51266f77159cb3227dd6997f839492907438f6bdb18feca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
